export const GET_PROJECT_DATA = 'GET_PROJECT_DATA'
export const GET_PROJECT_DATA_SUCCESS = 'GET_PROJECT_DATA_SUCCESS'
export const GET_PROJECT_DATA_FAILURE = 'GET_PROJECT_DATA_FAILURE'

export const GET_ARTIST_DATA = 'GET_ARTIST_DATA'
export const GET_ARTIST_DATA_SUCCESS = 'GET_ARTIST_DATA_SUCCESS'
export const GET_ARTIST_DATA_FAILURE = 'GET_ARTIST_DATA_FAILURE'